project:
    type: book
    output-dir: docs

book:
    title: "Data 100 Discussion Notes"
    author: Conan Smallwood
    search: 
      location: sidebar
      type: textbox
    chapters:
      - index.qmd
      - disc01/disc01.qmd
      - disc02/disc02.qmd
      - disc03/disc03.qmd
      - disc04/disc04.qmd
      - disc05/disc05.qmd
      - disc06/disc06.qmd
      - disc07/disc07.qmd